server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  flyway:
    enabled: true
    validate-on-migrate: true
    encoding: UTF-8
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: false
    validate-on-migrate: false
db:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user_bank
    password: userbank13!#
    url: jdbc:postgresql://mugu.synology.me:55432/bank
