server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  flyway:
    enabled: true
    validate-on-migrate: true
    encoding: UTF-8
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: false
